//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDopravniPodnik.RouteNumberService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteNumber", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.BusinessLayerClass")]
    [System.SerializableAttribute()]
    public partial class RouteNumber : WebDopravniPodnik.RouteNumberService1.DomainObject {
        
        private string _descriptionField;
        
        private int _idField;
        
        private int _numberField;
        
        private WebDopravniPodnik.RouteNumberService1.RouteNumberStation[] _routeNumberStationsDirectionOneField;
        
        private WebDopravniPodnik.RouteNumberService1.RouteNumberStation[] _routeNumberStationsDirectionTwoField;
        
        private WebDopravniPodnik.RouteNumberService1.Route[] _routesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _description {
            get {
                return this._descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this._descriptionField, value) != true)) {
                    this._descriptionField = value;
                    this.RaisePropertyChanged("_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _number {
            get {
                return this._numberField;
            }
            set {
                if ((this._numberField.Equals(value) != true)) {
                    this._numberField = value;
                    this.RaisePropertyChanged("_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.RouteNumberStation[] _routeNumberStationsDirectionOne {
            get {
                return this._routeNumberStationsDirectionOneField;
            }
            set {
                if ((object.ReferenceEquals(this._routeNumberStationsDirectionOneField, value) != true)) {
                    this._routeNumberStationsDirectionOneField = value;
                    this.RaisePropertyChanged("_routeNumberStationsDirectionOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.RouteNumberStation[] _routeNumberStationsDirectionTwo {
            get {
                return this._routeNumberStationsDirectionTwoField;
            }
            set {
                if ((object.ReferenceEquals(this._routeNumberStationsDirectionTwoField, value) != true)) {
                    this._routeNumberStationsDirectionTwoField = value;
                    this.RaisePropertyChanged("_routeNumberStationsDirectionTwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Route[] _routes {
            get {
                return this._routesField;
            }
            set {
                if ((object.ReferenceEquals(this._routesField, value) != true)) {
                    this._routesField = value;
                    this.RaisePropertyChanged("_routes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainObject", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.BusinessLayerClass")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDopravniPodnik.RouteNumberService1.RouteNumberStation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDopravniPodnik.RouteNumberService1.Station))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDopravniPodnik.RouteNumberService1.Route))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDopravniPodnik.RouteNumberService1.CustomerJourney))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDopravniPodnik.RouteNumberService1.Customer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDopravniPodnik.RouteNumberService1.Coupon))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDopravniPodnik.RouteNumberService1.Payment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDopravniPodnik.RouteNumberService1.Vehicle))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDopravniPodnik.RouteNumberService1.Employee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDopravniPodnik.RouteNumberService1.Driver))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDopravniPodnik.RouteNumberService1.RouteNumber))]
    public partial class DomainObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteNumberStation", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.BusinessLayerClass")]
    [System.SerializableAttribute()]
    public partial class RouteNumberStation : WebDopravniPodnik.RouteNumberService1.DomainObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double KmToNextStationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebDopravniPodnik.RouteNumberService1.Station StationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((this.DirectionField.Equals(value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double KmToNextStation {
            get {
                return this.KmToNextStationField;
            }
            set {
                if ((this.KmToNextStationField.Equals(value) != true)) {
                    this.KmToNextStationField = value;
                    this.RaisePropertyChanged("KmToNextStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order {
            get {
                return this.OrderField;
            }
            set {
                if ((this.OrderField.Equals(value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebDopravniPodnik.RouteNumberService1.Station Station {
            get {
                return this.StationField;
            }
            set {
                if ((object.ReferenceEquals(this.StationField, value) != true)) {
                    this.StationField = value;
                    this.RaisePropertyChanged("Station");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.BusinessLayerClass")]
    [System.SerializableAttribute()]
    public partial class Station : WebDopravniPodnik.RouteNumberService1.DomainObject {
        
        private float _gpslatField;
        
        private float _gpslngField;
        
        private int _idField;
        
        private string _nameField;
        
        private WebDopravniPodnik.RouteNumberService1.RouteNumberStation[] _routeNumberStationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float _gpslat {
            get {
                return this._gpslatField;
            }
            set {
                if ((this._gpslatField.Equals(value) != true)) {
                    this._gpslatField = value;
                    this.RaisePropertyChanged("_gpslat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float _gpslng {
            get {
                return this._gpslngField;
            }
            set {
                if ((this._gpslngField.Equals(value) != true)) {
                    this._gpslngField = value;
                    this.RaisePropertyChanged("_gpslng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.RouteNumberStation[] _routeNumberStations {
            get {
                return this._routeNumberStationsField;
            }
            set {
                if ((object.ReferenceEquals(this._routeNumberStationsField, value) != true)) {
                    this._routeNumberStationsField = value;
                    this.RaisePropertyChanged("_routeNumberStations");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Route", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.BusinessLayerClass")]
    [System.SerializableAttribute()]
    public partial class Route : WebDopravniPodnik.RouteNumberService1.DomainObject {
        
        private WebDopravniPodnik.RouteNumberService1.CustomerJourney[] _customerJourneysField;
        
        private System.DateTime _endRouteField;
        
        private int _idField;
        
        private WebDopravniPodnik.RouteNumberService1.RouteNumber _routeNumberField;
        
        private System.DateTime _startRouteField;
        
        private WebDopravniPodnik.RouteNumberService1.Vehicle _vehicleField;
        
        private WebDopravniPodnik.RouteNumberService1.Station currentStationField;
        
        private WebDopravniPodnik.RouteNumberService1.Driver driverField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.CustomerJourney[] _customerJourneys {
            get {
                return this._customerJourneysField;
            }
            set {
                if ((object.ReferenceEquals(this._customerJourneysField, value) != true)) {
                    this._customerJourneysField = value;
                    this.RaisePropertyChanged("_customerJourneys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _endRoute {
            get {
                return this._endRouteField;
            }
            set {
                if ((this._endRouteField.Equals(value) != true)) {
                    this._endRouteField = value;
                    this.RaisePropertyChanged("_endRoute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.RouteNumber _routeNumber {
            get {
                return this._routeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this._routeNumberField, value) != true)) {
                    this._routeNumberField = value;
                    this.RaisePropertyChanged("_routeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _startRoute {
            get {
                return this._startRouteField;
            }
            set {
                if ((this._startRouteField.Equals(value) != true)) {
                    this._startRouteField = value;
                    this.RaisePropertyChanged("_startRoute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Vehicle _vehicle {
            get {
                return this._vehicleField;
            }
            set {
                if ((object.ReferenceEquals(this._vehicleField, value) != true)) {
                    this._vehicleField = value;
                    this.RaisePropertyChanged("_vehicle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Station currentStation {
            get {
                return this.currentStationField;
            }
            set {
                if ((object.ReferenceEquals(this.currentStationField, value) != true)) {
                    this.currentStationField = value;
                    this.RaisePropertyChanged("currentStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Driver driver {
            get {
                return this.driverField;
            }
            set {
                if ((object.ReferenceEquals(this.driverField, value) != true)) {
                    this.driverField = value;
                    this.RaisePropertyChanged("driver");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerJourney", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.BusinessLayerClass")]
    [System.SerializableAttribute()]
    public partial class CustomerJourney : WebDopravniPodnik.RouteNumberService1.DomainObject {
        
        private string _commentField;
        
        private WebDopravniPodnik.RouteNumberService1.Customer _customerField;
        
        private WebDopravniPodnik.RouteNumberService1.Station _endStationField;
        
        private System.DateTime _exitDateField;
        
        private WebDopravniPodnik.RouteNumberService1.Payment _paymentField;
        
        private WebDopravniPodnik.RouteNumberService1.Route _routeField;
        
        private System.DateTime _startDateField;
        
        private WebDopravniPodnik.RouteNumberService1.Station _startStationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _comment {
            get {
                return this._commentField;
            }
            set {
                if ((object.ReferenceEquals(this._commentField, value) != true)) {
                    this._commentField = value;
                    this.RaisePropertyChanged("_comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Customer _customer {
            get {
                return this._customerField;
            }
            set {
                if ((object.ReferenceEquals(this._customerField, value) != true)) {
                    this._customerField = value;
                    this.RaisePropertyChanged("_customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Station _endStation {
            get {
                return this._endStationField;
            }
            set {
                if ((object.ReferenceEquals(this._endStationField, value) != true)) {
                    this._endStationField = value;
                    this.RaisePropertyChanged("_endStation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _exitDate {
            get {
                return this._exitDateField;
            }
            set {
                if ((this._exitDateField.Equals(value) != true)) {
                    this._exitDateField = value;
                    this.RaisePropertyChanged("_exitDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Payment _payment {
            get {
                return this._paymentField;
            }
            set {
                if ((object.ReferenceEquals(this._paymentField, value) != true)) {
                    this._paymentField = value;
                    this.RaisePropertyChanged("_payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Route _route {
            get {
                return this._routeField;
            }
            set {
                if ((object.ReferenceEquals(this._routeField, value) != true)) {
                    this._routeField = value;
                    this.RaisePropertyChanged("_route");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _startDate {
            get {
                return this._startDateField;
            }
            set {
                if ((this._startDateField.Equals(value) != true)) {
                    this._startDateField = value;
                    this.RaisePropertyChanged("_startDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Station _startStation {
            get {
                return this._startStationField;
            }
            set {
                if ((object.ReferenceEquals(this._startStationField, value) != true)) {
                    this._startStationField = value;
                    this.RaisePropertyChanged("_startStation");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.BusinessLayerClass")]
    [System.SerializableAttribute()]
    public partial class Customer : WebDopravniPodnik.RouteNumberService1.DomainObject {
        
        private string _adressField;
        
        private System.DateTime _birthDateField;
        
        private string _cityField;
        
        private WebDopravniPodnik.RouteNumberService1.Coupon[] _couponsField;
        
        private WebDopravniPodnik.RouteNumberService1.CustomerJourney[] _customerJourneysField;
        
        private string _emailField;
        
        private string _firstnameField;
        
        private int _idField;
        
        private string _lastnameField;
        
        private string _loginField;
        
        private string _passwordField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _adress {
            get {
                return this._adressField;
            }
            set {
                if ((object.ReferenceEquals(this._adressField, value) != true)) {
                    this._adressField = value;
                    this.RaisePropertyChanged("_adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _birthDate {
            get {
                return this._birthDateField;
            }
            set {
                if ((this._birthDateField.Equals(value) != true)) {
                    this._birthDateField = value;
                    this.RaisePropertyChanged("_birthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _city {
            get {
                return this._cityField;
            }
            set {
                if ((object.ReferenceEquals(this._cityField, value) != true)) {
                    this._cityField = value;
                    this.RaisePropertyChanged("_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Coupon[] _coupons {
            get {
                return this._couponsField;
            }
            set {
                if ((object.ReferenceEquals(this._couponsField, value) != true)) {
                    this._couponsField = value;
                    this.RaisePropertyChanged("_coupons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.CustomerJourney[] _customerJourneys {
            get {
                return this._customerJourneysField;
            }
            set {
                if ((object.ReferenceEquals(this._customerJourneysField, value) != true)) {
                    this._customerJourneysField = value;
                    this.RaisePropertyChanged("_customerJourneys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _email {
            get {
                return this._emailField;
            }
            set {
                if ((object.ReferenceEquals(this._emailField, value) != true)) {
                    this._emailField = value;
                    this.RaisePropertyChanged("_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _firstname {
            get {
                return this._firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this._firstnameField, value) != true)) {
                    this._firstnameField = value;
                    this.RaisePropertyChanged("_firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _lastname {
            get {
                return this._lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this._lastnameField, value) != true)) {
                    this._lastnameField = value;
                    this.RaisePropertyChanged("_lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _login {
            get {
                return this._loginField;
            }
            set {
                if ((object.ReferenceEquals(this._loginField, value) != true)) {
                    this._loginField = value;
                    this.RaisePropertyChanged("_login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _password {
            get {
                return this._passwordField;
            }
            set {
                if ((object.ReferenceEquals(this._passwordField, value) != true)) {
                    this._passwordField = value;
                    this.RaisePropertyChanged("_password");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coupon", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.BusinessLayerClass")]
    [System.SerializableAttribute()]
    public partial class Coupon : WebDopravniPodnik.RouteNumberService1.DomainObject {
        
        private System.DateTime _endvalidityField;
        
        private int _idField;
        
        private WebDopravniPodnik.RouteNumberService1.Customer _ownerField;
        
        private WebDopravniPodnik.RouteNumberService1.Payment _paymentField;
        
        private System.DateTime _startvalidityField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _endvalidity {
            get {
                return this._endvalidityField;
            }
            set {
                if ((this._endvalidityField.Equals(value) != true)) {
                    this._endvalidityField = value;
                    this.RaisePropertyChanged("_endvalidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Customer _owner {
            get {
                return this._ownerField;
            }
            set {
                if ((object.ReferenceEquals(this._ownerField, value) != true)) {
                    this._ownerField = value;
                    this.RaisePropertyChanged("_owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Payment _payment {
            get {
                return this._paymentField;
            }
            set {
                if ((object.ReferenceEquals(this._paymentField, value) != true)) {
                    this._paymentField = value;
                    this.RaisePropertyChanged("_payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _startvalidity {
            get {
                return this._startvalidityField;
            }
            set {
                if ((this._startvalidityField.Equals(value) != true)) {
                    this._startvalidityField = value;
                    this.RaisePropertyChanged("_startvalidity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.BusinessLayerClass")]
    [System.SerializableAttribute()]
    public partial class Payment : WebDopravniPodnik.RouteNumberService1.DomainObject {
        
        private WebDopravniPodnik.RouteNumberService1.Coupon _couponField;
        
        private int _idField;
        
        private WebDopravniPodnik.RouteNumberService1.CustomerJourney _journeyField;
        
        private WebDopravniPodnik.RouteNumberService1.Customer _payerField;
        
        private System.DateTime _paymentDateField;
        
        private decimal _valueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Coupon _coupon {
            get {
                return this._couponField;
            }
            set {
                if ((object.ReferenceEquals(this._couponField, value) != true)) {
                    this._couponField = value;
                    this.RaisePropertyChanged("_coupon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.CustomerJourney _journey {
            get {
                return this._journeyField;
            }
            set {
                if ((object.ReferenceEquals(this._journeyField, value) != true)) {
                    this._journeyField = value;
                    this.RaisePropertyChanged("_journey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Customer _payer {
            get {
                return this._payerField;
            }
            set {
                if ((object.ReferenceEquals(this._payerField, value) != true)) {
                    this._payerField = value;
                    this.RaisePropertyChanged("_payer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _paymentDate {
            get {
                return this._paymentDateField;
            }
            set {
                if ((this._paymentDateField.Equals(value) != true)) {
                    this._paymentDateField = value;
                    this.RaisePropertyChanged("_paymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal _value {
            get {
                return this._valueField;
            }
            set {
                if ((this._valueField.Equals(value) != true)) {
                    this._valueField = value;
                    this.RaisePropertyChanged("_value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicle", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.BusinessLayerClass")]
    [System.SerializableAttribute()]
    public partial class Vehicle : WebDopravniPodnik.RouteNumberService1.DomainObject {
        
        private string _brandField;
        
        private int _capacityField;
        
        private int _idField;
        
        private string _nameField;
        
        private WebDopravniPodnik.RouteNumberService1.Route[] _routesField;
        
        private string _spzField;
        
        private int _yearField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _brand {
            get {
                return this._brandField;
            }
            set {
                if ((object.ReferenceEquals(this._brandField, value) != true)) {
                    this._brandField = value;
                    this.RaisePropertyChanged("_brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _capacity {
            get {
                return this._capacityField;
            }
            set {
                if ((this._capacityField.Equals(value) != true)) {
                    this._capacityField = value;
                    this.RaisePropertyChanged("_capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Route[] _routes {
            get {
                return this._routesField;
            }
            set {
                if ((object.ReferenceEquals(this._routesField, value) != true)) {
                    this._routesField = value;
                    this.RaisePropertyChanged("_routes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _spz {
            get {
                return this._spzField;
            }
            set {
                if ((object.ReferenceEquals(this._spzField, value) != true)) {
                    this._spzField = value;
                    this.RaisePropertyChanged("_spz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _year {
            get {
                return this._yearField;
            }
            set {
                if ((this._yearField.Equals(value) != true)) {
                    this._yearField = value;
                    this.RaisePropertyChanged("_year");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.BusinessLayerClass")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebDopravniPodnik.RouteNumberService1.Driver))]
    public partial class Employee : WebDopravniPodnik.RouteNumberService1.DomainObject {
        
        private string _adressField;
        
        private System.DateTime _birthdateField;
        
        private string _cityField;
        
        private string _emailField;
        
        private string _firstnameField;
        
        private int _idField;
        
        private string _lastnameField;
        
        private string _loginField;
        
        private string _passwordField;
        
        private WebDopravniPodnik.RouteNumberService1.Route[] _routesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _adress {
            get {
                return this._adressField;
            }
            set {
                if ((object.ReferenceEquals(this._adressField, value) != true)) {
                    this._adressField = value;
                    this.RaisePropertyChanged("_adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _birthdate {
            get {
                return this._birthdateField;
            }
            set {
                if ((this._birthdateField.Equals(value) != true)) {
                    this._birthdateField = value;
                    this.RaisePropertyChanged("_birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _city {
            get {
                return this._cityField;
            }
            set {
                if ((object.ReferenceEquals(this._cityField, value) != true)) {
                    this._cityField = value;
                    this.RaisePropertyChanged("_city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _email {
            get {
                return this._emailField;
            }
            set {
                if ((object.ReferenceEquals(this._emailField, value) != true)) {
                    this._emailField = value;
                    this.RaisePropertyChanged("_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _firstname {
            get {
                return this._firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this._firstnameField, value) != true)) {
                    this._firstnameField = value;
                    this.RaisePropertyChanged("_firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _id {
            get {
                return this._idField;
            }
            set {
                if ((this._idField.Equals(value) != true)) {
                    this._idField = value;
                    this.RaisePropertyChanged("_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _lastname {
            get {
                return this._lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this._lastnameField, value) != true)) {
                    this._lastnameField = value;
                    this.RaisePropertyChanged("_lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _login {
            get {
                return this._loginField;
            }
            set {
                if ((object.ReferenceEquals(this._loginField, value) != true)) {
                    this._loginField = value;
                    this.RaisePropertyChanged("_login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _password {
            get {
                return this._passwordField;
            }
            set {
                if ((object.ReferenceEquals(this._passwordField, value) != true)) {
                    this._passwordField = value;
                    this.RaisePropertyChanged("_password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WebDopravniPodnik.RouteNumberService1.Route[] _routes {
            get {
                return this._routesField;
            }
            set {
                if ((object.ReferenceEquals(this._routesField, value) != true)) {
                    this._routesField = value;
                    this.RaisePropertyChanged("_routes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Driver", Namespace="http://schemas.datacontract.org/2004/07/BusinessLayer.BusinessLayerClass")]
    [System.SerializableAttribute()]
    public partial class Driver : WebDopravniPodnik.RouteNumberService1.Employee {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RouteNumberService1.IRouteNumberService")]
    public interface IRouteNumberService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteNumberService/GetAll", ReplyAction="http://tempuri.org/IRouteNumberService/GetAllResponse")]
        WebDopravniPodnik.RouteNumberService1.RouteNumber[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteNumberService/GetAll", ReplyAction="http://tempuri.org/IRouteNumberService/GetAllResponse")]
        System.Threading.Tasks.Task<WebDopravniPodnik.RouteNumberService1.RouteNumber[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteNumberService/Load", ReplyAction="http://tempuri.org/IRouteNumberService/LoadResponse")]
        WebDopravniPodnik.RouteNumberService1.RouteNumber Load(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteNumberService/Load", ReplyAction="http://tempuri.org/IRouteNumberService/LoadResponse")]
        System.Threading.Tasks.Task<WebDopravniPodnik.RouteNumberService1.RouteNumber> LoadAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteNumberService/GetRNSDirectionOne", ReplyAction="http://tempuri.org/IRouteNumberService/GetRNSDirectionOneResponse")]
        WebDopravniPodnik.RouteNumberService1.RouteNumberStation[] GetRNSDirectionOne(int routeNumberID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteNumberService/GetRNSDirectionOne", ReplyAction="http://tempuri.org/IRouteNumberService/GetRNSDirectionOneResponse")]
        System.Threading.Tasks.Task<WebDopravniPodnik.RouteNumberService1.RouteNumberStation[]> GetRNSDirectionOneAsync(int routeNumberID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteNumberService/GetRNSDirectionTwo", ReplyAction="http://tempuri.org/IRouteNumberService/GetRNSDirectionTwoResponse")]
        WebDopravniPodnik.RouteNumberService1.RouteNumberStation[] GetRNSDirectionTwo(int routeNumberID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteNumberService/GetRNSDirectionTwo", ReplyAction="http://tempuri.org/IRouteNumberService/GetRNSDirectionTwoResponse")]
        System.Threading.Tasks.Task<WebDopravniPodnik.RouteNumberService1.RouteNumberStation[]> GetRNSDirectionTwoAsync(int routeNumberID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRouteNumberServiceChannel : WebDopravniPodnik.RouteNumberService1.IRouteNumberService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RouteNumberServiceClient : System.ServiceModel.ClientBase<WebDopravniPodnik.RouteNumberService1.IRouteNumberService>, WebDopravniPodnik.RouteNumberService1.IRouteNumberService {
        
        public RouteNumberServiceClient() {
        }
        
        public RouteNumberServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RouteNumberServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteNumberServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RouteNumberServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebDopravniPodnik.RouteNumberService1.RouteNumber[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<WebDopravniPodnik.RouteNumberService1.RouteNumber[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public WebDopravniPodnik.RouteNumberService1.RouteNumber Load(int id) {
            return base.Channel.Load(id);
        }
        
        public System.Threading.Tasks.Task<WebDopravniPodnik.RouteNumberService1.RouteNumber> LoadAsync(int id) {
            return base.Channel.LoadAsync(id);
        }
        
        public WebDopravniPodnik.RouteNumberService1.RouteNumberStation[] GetRNSDirectionOne(int routeNumberID) {
            return base.Channel.GetRNSDirectionOne(routeNumberID);
        }
        
        public System.Threading.Tasks.Task<WebDopravniPodnik.RouteNumberService1.RouteNumberStation[]> GetRNSDirectionOneAsync(int routeNumberID) {
            return base.Channel.GetRNSDirectionOneAsync(routeNumberID);
        }
        
        public WebDopravniPodnik.RouteNumberService1.RouteNumberStation[] GetRNSDirectionTwo(int routeNumberID) {
            return base.Channel.GetRNSDirectionTwo(routeNumberID);
        }
        
        public System.Threading.Tasks.Task<WebDopravniPodnik.RouteNumberService1.RouteNumberStation[]> GetRNSDirectionTwoAsync(int routeNumberID) {
            return base.Channel.GetRNSDirectionTwoAsync(routeNumberID);
        }
    }
}
